// Generates llms.txt — an LLM-ingestible Markdown doc following the llms.txt convention.
// All values come from deck; no network calls, no eval.

function safe(v, fallback = '') {
  if (v === null || v === undefined) return fallback;
  return String(v).replace(/[<>]/g, '');
}

function safeList(arr, fallback = 'Not provided') {
  if (!Array.isArray(arr) || arr.length === 0) return fallback;
  return arr.map((item) => `- ${safe(item)}`).join('\n');
}

export function generateLlmsTxt(deck) {
  const c = deck.company ?? {};
  const f = deck.fundraising ?? {};
  const t = deck.traction ?? {};
  const m = deck.market ?? {};
  const links = deck.links ?? {};
  const team = deck.team ?? [];

  const teamLines = team.map((member) => {
    const name = safe(member?.name, 'Unknown');
    const role = safe(member?.role, '');
    const bg = safe(member?.background, '');
    return `- **${name}** (${role}): ${bg}`;
  }).join('\n');

  const competitors = Array.isArray(m.competitors)
    ? m.competitors.map((c) => safe(c)).join(', ')
    : safe(m.competitors, 'Not listed');

  return `# ${safe(c.name, 'Company')}

> ${safe(c.one_liner, 'No one-liner provided.')}

## The Raise

- **Round:** ${safe(f.round, 'Not specified')}
- **Target:** ${safe(f.target_raise, 'Not specified')}
- **Instrument:** ${safe(f.instrument, 'Not specified')}
- **Use of funds:**
${safeList(f.use_of_funds, '- Not specified')}

## Key Metrics

- **MRR:** ${safe(t.mrr, 'Not disclosed')}${t.mrr_date ? ` (as of ${safe(t.mrr_date)})` : ''}
- **Growth rate:** ${safe(t.growth_rate, 'Not disclosed')}
- **Customers:** ${safe(t.customers, 'Not disclosed')}
- **Pilots:** ${safe(t.pilots, 'Not disclosed')}

## Market

- **ICP:** ${safe(m.icp, 'Not specified')}
- **Pain:** ${safe(m.pain, 'Not specified')}
- **Market size:** ${safe(m.market_size, 'Not specified')}${m.market_size_source ? ` (source: ${safe(m.market_size_source)})` : ''}
- **Competitors:** ${competitors}
- **Differentiation:** ${safe(m.differentiation, 'Not specified')}

## Team

${teamLines || '- No team members listed'}

## Links

- **Deck:** ${safe(links.docsend, 'Not provided')}
- **Demo:** ${safe(links.demo, 'Not provided')}
- **Calendly:** ${safe(links.calendly, 'Not provided')}
- **Contact:** ${safe(links.contact, 'Not provided')}
- **Website:** ${safe(c.website, 'Not provided')}

---
*Generated by [deckcheck](https://github.com/yigitmeteozcan/deckcheck). This file is machine-readable — do not modify manually.*
`;
}
