// Generates investor-summary.md — a human-readable one-pager a VC could skim.

function safe(v, fallback = 'Not provided') {
  if (v === null || v === undefined) return fallback;
  return String(v).replace(/[<>]/g, '');
}

function safeList(arr, fallback = 'Not specified') {
  if (!Array.isArray(arr) || arr.length === 0) return fallback;
  return arr.map((item) => `- ${safe(item)}`).join('\n');
}

export function generateSummaryMd(deck) {
  const c = deck.company ?? {};
  const f = deck.fundraising ?? {};
  const t = deck.traction ?? {};
  const m = deck.market ?? {};
  const links = deck.links ?? {};
  const team = deck.team ?? [];

  const stage = c.stage ? ` · ${safe(c.stage)}` : '';
  const category = c.category ? ` · ${safe(c.category)}` : '';

  const teamSection = team.length > 0
    ? team.map((member) => {
        const name = safe(member?.name, 'Unknown');
        const role = safe(member?.role, 'Unknown role');
        const bg = safe(member?.background, '');
        return `**${name}**, ${role}${bg ? ' — ' + bg : ''}`;
      }).join('\n\n')
    : 'No team members listed.';

  const competitors = Array.isArray(m.competitors) && m.competitors.length > 0
    ? m.competitors.map((c) => safe(c)).join(', ')
    : 'None listed';

  const date = new Date().toISOString().slice(0, 10);

  return `# ${safe(c.name, 'Company')} — Investor Summary

*${safe(c.one_liner, 'No one-liner provided.')}*

${safe(c.website)}${stage}${category}

---

## The Raise

| | |
|---|---|
| **Round** | ${safe(f.round)} |
| **Target** | ${safe(f.target_raise)} |
| **Instrument** | ${safe(f.instrument)} |

**Use of funds:**

${safeList(f.use_of_funds)}

---

## Traction

| Metric | Value |
|---|---|
| **MRR** | ${safe(t.mrr)}${t.mrr_date ? ` *(as of ${safe(t.mrr_date)})*` : ''} |
| **Growth** | ${safe(t.growth_rate)} |
| **Customers** | ${safe(t.customers)} |
| **Pilots** | ${safe(t.pilots)} |

---

## Market

**ICP:** ${safe(m.icp)}

**Pain:** ${safe(m.pain)}

**Market size:** ${safe(m.market_size)}${m.market_size_source ? ` *(${safe(m.market_size_source)})*` : ''}

**Competitors:** ${competitors}

**Why we win:** ${safe(m.differentiation)}

---

## Team

${teamSection}

---

## Links

| | |
|---|---|
| **Deck** | ${safe(links.docsend)} |
| **Demo** | ${safe(links.demo)} |
| **Calendly** | ${safe(links.calendly)} |
| **Contact** | ${safe(links.contact)} |

---

*Generated by pitchlint on ${date}. Data sourced from deck.yml — verify before distributing.*
`;
}
